feat(decision-tree): add decision tree visualisation
molgenis/vip-report-template pull request #160
Opened 2021-07-06 14:24 UTC by marikaris

2021-07-07 05:55 UTC, dennishendriksen requested changes

2021-07-07 05:55 UTC, dennishendriksen commented on .eslintrc.js
> +    '@typescript-eslint/no-var-requires': 0,
Why make changes to the .eslintrc.js? My preference would be to keep it consistent across our Typescript projects.

2021-07-07 05:55 UTC, dennishendriksen commented on .gitignore
> +yarn.lock
This project uses npm instead of yarn, so why ignore yarn.lock?

2021-07-07 05:55 UTC, dennishendriksen commented on package.json
> +    "@types/dagre": "^0.7.44",
You might want to bump this dependency to ^0.7.45

2021-07-07 05:55 UTC, dennishendriksen commented on package.json
> +    "@types/d3-shape": "^3.0.0",
Is this dev dependency required since you don't have a dependency on `d3-shape`?
Alternatively, can the d3 dependency be replaced with only d3-shape?

2021-07-07 05:55 UTC, dennishendriksen commented on package.json
> +    "@types/d3-zoom": "^3.0.1",
Is this dev dependency required since you don't have a dependency on `d3-zoom`?
Alternatively, can the d3 dependency be replaced with only d3-zoom?

2021-07-07 05:55 UTC, dennishendriksen commented on package.json
> +    "@types/d3-shape": "^3.0.0",
You might want to bump this dependency to ^3.0.1

2021-07-07 05:55 UTC, dennishendriksen commented on src/components/NavigationBar.vue
> +          <b-dropdown-item :to="{ name: 'decision-tree' }">{{ $t('treeViewer') }}</b-dropdown-item>
This menu entry shouldn't be added to the menu if no decision tree is available

2021-07-07 05:55 UTC, dennishendriksen commented on src/components/TreeVisualisation.vue
> +      default: '#6c757d'
is it possible to add a class instead of hardcoding the color and move the styling to App.vue that contains all styling for the template?

2021-07-07 05:55 UTC, dennishendriksen commented on src/components/TreeVisualisation.vue
> +      default: '#fff'
is it possible to add a class instead of hardcoding the color and move the styling to App.vue that contains all styling for the template?

2021-07-07 05:55 UTC, dennishendriksen commented on src/components/TreeVisualisation.vue
> +.d3-tree-visualisation {
Currently all styling information is stored in App.vue. To keep it consistent I suggest to move this to App.vue as well.

2021-07-07 05:55 UTC, dennishendriksen commented on src/components/TreeVisualisation.vue
> +      return fontSize ? Number(fontSize.replace('px', '')) : 10;
This VUE app uses REMs instead of px (see App.vue), don't mix them together.

2021-07-07 05:55 UTC, dennishendriksen commented on src/store/actions.ts
> +  getDecisionTree(): Promise<Buffer | null> {
I think it would be better to return an object here containing the JSON of the unzipped tree. The zipped string is not useful for the user. Although a use case might be to provide a download button for the tree in the tree viewer, in this case returning a unzipped tree would be better and the JSON.parse would still happen in the components using this action.

In case we decide not to change the return type then please rename getDecisionTree to getDecisionTreeGz

2021-07-07 05:55 UTC, dennishendriksen commented on src/store/getters.ts
> +  getSampleById:
any clue why the formatting changed in this file? I don't think you made any other changes to this file, so I propose to revert.

2021-07-07 05:55 UTC, dennishendriksen commented on src/types/DecisionTree.d.ts
> +type Outcome = {
I think this type should be in `vip-report-api` instead of `vip-report-template` so that other templates that want to do something with the decision tree can use it as well.

2021-07-07 05:55 UTC, dennishendriksen commented on src/types/DecisionTree.d.ts
> +  class: 'T' | 'F';
a decision tree doesn't necessarily have T and F classes for exist node. I can have any classes, for example B/LB/VUS/LP/P.

2021-07-07 05:55 UTC, dennishendriksen commented on tsconfig.json
> +    "skipLibCheck": true,
can you explain why you made changes in this file?

2021-07-08 06:26 UTC, marikaris commented on .gitignore
> +yarn.lock
I personally use yarn because npm doesnt always work that well on my machine. Many times I almost added yarn.lock on git. It's very annoying and this makes sure I won't make that mistake.

2021-07-08 06:28 UTC, marikaris commented on package.json
> +    "@types/dagre": "^0.7.44",
Good point, when I added it, this was the newest version. I'll bump it.

2021-07-08 06:43 UTC, marikaris commented on package.json
> +    "@types/d3-shape": "^3.0.0",
Yes and no. It's a dev dependency on the types of d3 shape. It was needed to be able to import the line like this:
`import { line } from 'd3-shape';`
That way of importing makes sure we don't import more resources than we need.

2021-07-08 09:06 UTC, marikaris commented on package.json
> +    "@types/d3-zoom": "^3.0.1",
Same as above, it's because I use this way of importing to minimize resources.

2021-07-08 12:03 UTC, marikaris commented on src/store/getters.ts
> +  getSampleById:
Honestly because I can't get webstorm to stop reformatting my files. I'll try to exclude it. When I noticed this file was in there, it was already done. Whenever I paste the original over it, it automatically saves an reformats, no matter what I do :(

2021-07-08 12:12 UTC, marikaris commented on src/store/getters.ts
> +  getSampleById:
I removed it now. I see I did it to fix 31 eslint warnings. Please let me know if you want to keep it excluded and have the warnings or if you want me to fix them.

2021-07-08 12:16 UTC, marikaris commented on tsconfig.json
> +    "skipLibCheck": true,
without this I get typescript errors in library files (d3 and dagre):
```
ERROR in /Users/mslofstra/git/vip-report-template/src/types/d3.d.ts(6,5):
6:5 Type 'Selection' is not generic.
    4 |   | d3Selection<Element, never, null, never>
    5 |   | Record<string, never>
  > 6 |   | Selection<SVGSVGElement, unknown, null, undefined>;
      |     ^
    7 | 
ERROR in /Users/mslofstra/git/vip-report-template/src/types/dagre.d.ts(1,23):
1:23 Could not find a declaration file for module 'graphlib'. '/Users/mslofstra/git/vip-report-template/node_modules/graphlib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/graphlib` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphlib';`
  > 1 | import { Graph } from 'graphlib';
      |                       ^
    2 | 
    3 | export type TreeGraph = Graph | Graph<Record<string, never>>;

```
This makes it impossible to run the template

2021-07-08 12:21 UTC, marikaris commented on src/types/DecisionTree.d.ts
> +type Outcome = {
Partly maybe, but not completely, there are some generic types in there as well. I really tried to separate the tree part from the decision tree part. The tree part should also work for any other tree as long as you provide the correct input data. 
The api however has zipped data, so I'm not entirely sure how you would include this typing in that repository

2021-07-09 05:34 UTC, dennishendriksen requested changes

2021-07-09 05:34 UTC, dennishendriksen commented on src/components/NavigationBar.vue
> +          <b-dropdown-item :to="{ name: 'decision-tree' }">{{ $t('treeViewer') }}</b-dropdown-item>
I think not adding the menu entry via a `hasDecisionTree` is a bit nicer for the user than adding the entry and seeing a 'it is unavailable' message.

2021-07-09 05:34 UTC, dennishendriksen commented on src/types/DecisionTree.d.ts
> +type Outcome = {
> so I'm not entirely sure how you would include this typing in that repository

add it to one of the existing files that only exports types. we could also choose to do this later once we have more than one template. how about creating an enhancement issue for this?

2021-07-09 05:34 UTC, dennishendriksen commented on tsconfig.json
> +    "skipLibCheck": true,
maybe check with @jelmerveen is this can be resolved in another way without disabling all library checks?

2021-07-09 05:36 UTC, dennishendriksen commented on src/views/DecisionTreeViewer.vue
> +<template>
Is it possible to colour exit nodes differently from non-exit blocks? possible the root node as well.

2021-07-09 08:29 UTC, jelmerveen commented on tsconfig.json
> +    "skipLibCheck": true,
https://www.npmjs.com/package/@types/graphlib fixes the second part of the problem.

2021-07-09 08:32 UTC, jelmerveen commented on tsconfig.json
> +    "skipLibCheck": true,
educated guess for selection type error: https://www.npmjs.com/package/@types/d3-selection

2021-07-09 12:37 UTC, marikaris commented on tsconfig.json
> +    "skipLibCheck": true,
Thanks! I'll take a look at it.

2021-07-13 06:11 UTC, marikaris commented on src/components/TreeVisualisation.vue
> +      return fontSize ? Number(fontSize.replace('px', '')) : 10;
The whole graph is pixel based. It's not possible to use rems in the graphs. The fontsize is used to determine the size of the whole graph, so we need to use pixels, I will change the css of the fontsize to REMs though, the component will automatically convert it from REM's to pixels to use in the graph

2021-07-20 13:05 UTC, svandenhoek commented on src/App.vue
> +}
Duplicate selector. I'd suggest merging these.

2021-07-27 08:54 UTC, svandenhoek approved these changes

2021-07-27 08:58 UTC, merged