Improve genotype quality filtering
molgenis/vip-report-template pull request #239
Opened 2022-10-10 11:11 UTC by bartcharbon

2022-10-24 12:14 UTC, dennishendriksen commented on src/components/VariantSampleTable.tsx
> -                          allelicDepth={props.record.data.s[props.samples[i()].index]["AD"] as number[]}
`ValueInteger[]` instead of `number[]`?

2022-10-24 12:14 UTC, dennishendriksen commented on src/components/VariantSampleTable.tsx
> +                          allelicBalance={props.record.data.s[props.samples[i()].index]["VIAB"] as number}
can be `null`?
can be `undefined`?

2022-10-24 12:14 UTC, dennishendriksen commented on src/components/filter/AllelicBalanceFilter.tsx
> +          { selector: ["s", sampleId, "VIAB"], operator: ">=", args: 0.2 },
since the number is float `=` doesn't make a lot of sense. how about > 0.2 and < 0.8?

2022-10-24 12:14 UTC, dennishendriksen commented on src/components/filter/AllelicBalanceFilter.tsx
> +      desc="Filter variants with allelic imbalance"
add our definition of allelic imbalance to filter description?

2022-10-24 12:14 UTC, dennishendriksen commented on src/components/record/Format.tsx
> +  allelicBalance: number | undefined;
`| null`?

2022-10-24 12:14 UTC, dennishendriksen commented on src/components/record/format/GenotypeField.tsx
> +function isAllelicImbalance(genotype: Genotype, allelicBalance: number | undefined) {
can allelicBalance be `null` here?

2022-10-24 12:14 UTC, dennishendriksen commented on src/components/record/format/GenotypeField.tsx
> +    return allelicBalance <= 0.2 || allelicBalance >= 0.8;
see previous comment on < > instead <= >=

2022-10-24 12:14 UTC, dennishendriksen commented on src/components/record/format/GenotypeField.tsx
> +  allelicBalance: number | undefined;
how about `| null` here?

2022-10-24 12:14 UTC, dennishendriksen commented on src/components/filter/Filter.tsx
> +export type SimpleFilterChangeEvent = { query: QueryClause };
is the `Simple*` change still necessary?

2022-10-24 12:18 UTC, bartcharbon commented on src/components/filter/AllelicBalanceFilter.tsx
> +          { selector: ["s", sampleId, "VIAB"], operator: ">=", args: 0.2 },
?

2022-10-24 12:24 UTC, bartcharbon commented on src/components/filter/AllelicBalanceFilter.tsx
> +          { selector: ["s", sampleId, "VIAB"], operator: ">=", args: 0.2 },
that float can still have exactly that value right?

2022-10-24 12:26 UTC, dennishendriksen commented on src/components/filter/AllelicBalanceFilter.tsx
> +          { selector: ["s", sampleId, "VIAB"], operator: ">=", args: 0.2 },
```
(0.3 * 3) + 0.1 === 1
false
```

2022-10-24 12:38 UTC, bartcharbon commented on src/components/VariantSampleTable.tsx
> -                          allelicDepth={props.record.data.s[props.samples[i()].index]["AD"] as number[]}
? this line is removed...

2022-10-24 12:52 UTC, bartcharbon commented on src/components/filter/Filter.tsx
> +export type SimpleFilterChangeEvent = { query: QueryClause };
Yes, the "standard" sample and info filters use this, it support the queryclause instead of query, the InfoFilters and SampleFilters components map it to the none-Simple variant, so the rest of the code can work in a uniform way

2022-10-24 13:20 UTC, dennishendriksen commented on src/components/VariantSampleTable.tsx
> -                          allelicDepth={props.record.data.s[props.samples[i()].index]["AD"] as number[]}
my bad

2022-10-25 06:02 UTC, dennishendriksen requested changes

2022-10-25 14:09 UTC, bartcharbon commented on src/components/VariantSampleTable.tsx
> +                          allelicBalance={
fixed

2022-10-25 14:11 UTC, bartcharbon commented on src/components/filter/InfoFilter.tsx
> +        ...(event.query as QueryClause),
in practice its always a QueryClause here, which implements query. Query has nog "selector" so can't be used here. I had trouble getting a working typecheck in here...

2022-10-27 06:02 UTC, dennishendriksen approved these changes

2022-10-27 06:02 UTC, merged